package LainEditor;

import javax.swing.JOptionPane;

/**
 *
 * @author luna
 */
public class Ventana extends javax.swing.JFrame {

    ManipulacionFicheros mf = new ManipulacionFicheros();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_Guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_GuardarComo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tzta_editorcontenido = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_NuevoArchivo = new javax.swing.JMenuItem();
        mn_Abrir = new javax.swing.JMenuItem();
        mn_Guardar = new javax.swing.JMenuItem();
        mn_GuardarComo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LainEditor");

        jToolBar1.setRollover(true);

        btn_Guardar.setText("Guardar");
        btn_Guardar.setFocusable(false);
        btn_Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Guardar);
        jToolBar1.add(jLabel1);

        btn_GuardarComo.setText("Guardar Como");
        btn_GuardarComo.setFocusable(false);
        btn_GuardarComo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_GuardarComo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_GuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarComoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_GuardarComo);

        tzta_editorcontenido.setColumns(20);
        tzta_editorcontenido.setRows(5);
        jScrollPane3.setViewportView(tzta_editorcontenido);

        jMenu1.setText("File");

        mn_NuevoArchivo.setText("Nuevo Archivo");
        mn_NuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_NuevoArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(mn_NuevoArchivo);

        mn_Abrir.setText("Abrir");
        mn_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_AbrirActionPerformed(evt);
            }
        });
        jMenu1.add(mn_Abrir);

        mn_Guardar.setText("Guardar");
        mn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_GuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mn_Guardar);

        mn_GuardarComo.setText("Guardar Como");
        mn_GuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_GuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(mn_GuardarComo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem5.setText("Acerca De");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Documentacion");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_AbrirActionPerformed
        mf.abrirArchivo();
        setTitle("LainEditor ["+mf.ArchivoSeleccionado.getName()+"]");
        tzta_editorcontenido.setText(mf.getContenido());
    }//GEN-LAST:event_mn_AbrirActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        mf.guardarArchivo(tzta_editorcontenido.getText());
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void mn_NuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_NuevoArchivoActionPerformed
        mf.nuevoArchivo();
        setTitle("LainEditor ["+mf.ArchivoSeleccionado.getName()+"]");
    }//GEN-LAST:event_mn_NuevoArchivoActionPerformed

    private void mn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_GuardarActionPerformed
        mf.guardarArchivo(tzta_editorcontenido.getText());
    }//GEN-LAST:event_mn_GuardarActionPerformed

    private void mn_GuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_GuardarComoActionPerformed
        mf.guardarComo(tzta_editorcontenido.getText());
    }//GEN-LAST:event_mn_GuardarComoActionPerformed

    private void btn_GuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarComoActionPerformed
        mf.guardarComo(tzta_editorcontenido.getText());
    }//GEN-LAST:event_btn_GuardarComoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(null, "Un proyecto creado por: \n Luna (Ludwing, Java Dev Junior) \n Gappy (Anderson, Java Dev Junior) \n como proyecto personal para nuestro portafolio", "Creadores", 1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JOptionPane.showMessageDialog(null, "Puedes Ver la Documentacion aquí \n --> ", "Documentación", 1);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_GuardarComo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mn_Abrir;
    private javax.swing.JMenuItem mn_Guardar;
    private javax.swing.JMenuItem mn_GuardarComo;
    private javax.swing.JMenuItem mn_NuevoArchivo;
    private javax.swing.JTextArea tzta_editorcontenido;
    // End of variables declaration//GEN-END:variables
}
